---
- hosts: kvm
  any_errors_fatal: true
  gather_facts: no
  become: yes
  roles:
    - master-deploy
    - worker-deploy

- name: Install Kubernetes 
  import_playbook: ../../kubernetes-deploy/deployment.yaml
