---
- hosts: localhost
  name: Cluster Status
  gather_facts: no
  vars:
    keytype: ipworker1-2

  tasks:
   - name: Create Kubernetes Worker Node VM directory
     file:
       dest: "/var/lib/libvirt/images/manish/{{item.ipwroker1}}"
       state: directory
     loop: "{{ lookup('file', '../lab_inventory/group_vars/all', wantlist=True) }}"
     when: "keytype | regex_search('ipworker[0-9]')"
