---
- hosts: localhost
  name: ori cluster info
  gather_facts: no
  vars:
    apikey: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJqUTNNemRGTURSR01VVTJRa1l5UXpZeE5VRkROMEl6UTBZeE1ESXdNalUxTmpsRU0wTTFRUSJ9.eyJodHRwczovL29yaS5jby91c2VyIjp7ImVtYWlsIjoicHJhZGVlcG5hcmF0QHZtd2FyZS5jb20iLCJuYW1lIjoicHJhZGVlcG5hcmF0QHZtd2FyZS5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvNDU1ZmQ4OGEzZDljYjBlYmI0ZGQ4ODIzOTEyNzI0ZDg_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZwci5wbmcifSwiZW1haWwiOiJwcmFkZWVwbmFyYXRAdm13YXJlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL29yaS1lZGdlLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2MjQ3MTQ4NzM1NjM1NzAwNmZkNDdhMDkiLCJhdWQiOiJnTnFGV3NtZXVTS2N2OTdNNXFQdFJaVDhFQXcyUDlIaiIsImlhdCI6MTY1MDk1NTU5OCwiZXhwIjoxNjUwOTU3Mzk4LCJub25jZSI6IlkyeDlrK3MvUkFuVExVWkowc01ta3c9PSJ9.TTsqjwUxsNnGRh4nI_bE9YT1e84tNTnk-g_Of3kQu0hU-UCKeapUGB0DrU7BwudyJKAL-G9DlhwaMFe9Plys6XipW1bguo75mcAYjqgQ5uuSxDu8JtBuSIeiTNTi9twcz0O3MG7CZU_LbNpt-_mP6n-YYc862PtVNzhzX7STgP8lh8481t63nk5TUKA4tQuhWl3Zb3RWx18gmk8_dGcy26c-RZlYiMut5w5jA4QczLJcdjXoUNMKCsXUF-ZBMSeJqML7F0O6dbm4uOG1fFi9n2HyJBh9x8ckmynm0nVcPHfPrLz3TxTlhR07h_EQDuRkzk9pH1erWnQjMLPB5qt9Vg
  tasks:
  - name: list all ori clusters 
    shell:
      "curl -X GET 'https://api-gateway.oriedge.net/v1/organisations/vmware/projects/caeb88f0-3431-4bf3-95ce-3f9e8e4fe1f7/clusters' -H 'Authorization: Bearer {{ apikey }}' > /tmp/ori.json" 
    register: curloutput
  - name: Display the file
    shell: "cat /tmp/ori.json"
    register: catfile
  - name : read file
    debug: 
      msg: "{{catfile.stdout_lines}}"
